apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-api
  namespace: of-fiap

spec:
  replicas: 2

  selector:
    matchLabels:
      app: spring-api

  template:
    metadata:
      labels:
        app: spring-api

    spec:
      containers:

        - name: spring-api

          image: ghcr.io/ramos1gabriel/oficina_fiap/spring-api:aws

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          envFrom:

            - configMapRef:
                name: spring-api-config

            - secretRef:
                name: spring-api-secret

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"

            limits:
              memory: "512Mi"
              cpu: "500m"

          readinessProbe:

            httpGet:
              path: /actuator/health/readiness
              port: 8080

            initialDelaySeconds: 240
            periodSeconds: 40

          livenessProbe:

            httpGet:
              path: /actuator/health/liveness
              port: 8080

            initialDelaySeconds: 360
            periodSeconds: 40
